cards/urls.py
from django.urls import path

from . import views

app_name = 'cards'
urlpatterns = [
    path('', views.index, name='index'),
    path('play', views.play, name='play'),
    path('how-to-play', views.how_to_play, name='how_to_play'),
    path('about', views.about, name='about'),
    path('suggest', views.suggest, name='suggest'),
    path('question-bank', views.question_bank, name='question_bank'),
]

christian_connection_cards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cards.urls'))
]

cards/models.py
from django.db import models

# Create your models here.

cards/views.py
import os
import json
import random
import functools
from collections import Counter
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings

QUESTIONS_PATH = os.path.join(settings.STATIC_ROOT, 'cards/questions.json')


def index(request):
    if request.method == 'POST':
        request.session['num_cards'] = request.POST['num_cards']
        return HttpResponseRedirect(reverse('cards:play'))
    
    # Randomise hero image selection
    image_list = ['1.svg', '2.svg', '3.svg', '4.svg', '5.svg', '6.svg', '7.svg']
    random_image = random.choice(image_list)

    # Define max range for questions
    with open(QUESTIONS_PATH, 'r') as json_file:
        questions = json.load(json_file)
    max_card_range_number = max_cards(questions) - (max_cards(questions) % 3)

    context = {
        'random_image': random_image,
        'max_cards': max_card_range_number,
        'default_cards': max_card_range_number // 2,
    }

    return render(request, 'cards/index.html', context)


def play(request):
    # Define max range for questions
    with open(QUESTIONS_PATH, 'r') as json_file:
        questions = json.load(json_file)
    max_card_range_number = max_cards(questions)
    num_cards = request.session.get('num_cards', str(max_card_range_number // 2))
    filtered_questions = generate_questions(questions, int(num_cards))
    
    context = {
        'num_cards': functools.reduce(lambda a, b: a if a > b['index'] else b['index'], filtered_questions, 0),
        'serialised_questions': json.dumps(filtered_questions),
    }

    return render(request, 'cards/play.html', context)

def how_to_play(request):
    return render(request, 'cards/how_to_play.html', {})

def about(request):
    return render(request, 'cards/about.html', {})

def suggest(request):
    return render(request, 'cards/suggest.html', {})

def question_bank(request):
    with open(QUESTIONS_PATH, 'r') as json_file:
        questions = json.load(json_file)
    context = {
        'questions': questions,
    }
    return render(request, 'cards/question_bank.html', context)


def generate_questions(questions, n):
    random.shuffle(questions)
    filtered_questions = []
    question_index = 1

    for stage in range(1,4):
        question_list_for_stage = [q['question'] for q in questions if q['stage'] == stage]
        filtered_question_list_for_stage = question_list_for_stage[:n]
        for filtered_question in filtered_question_list_for_stage:
            filtered_questions.append({
                'index': question_index,
                'stage': stage,
                'question': filtered_question,
            })
            question_index+=1
    
    return filtered_questions

def max_cards(questions):
    stage_occurrences = [question['stage'] for question in questions]
    stage_counter = Counter(stage_occurrences)
    max_cards = min(stage_counter.values())
    return max_cards

cards/templates/cards/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock title %}
{% block content %}
<section class="mx-auto px-5 md:px-20 min-w-5xl max-w-full py-10">
    <div class="hero">
        <div class="hero-content lg:max-w-3xl text-center">
            <div>
                <h1 class="text-3xl md:text-5xl font-black">About Christian Connection Cards</h1>
                <img src="{% static 'images/about.svg' %}" alt="Illustration of a human by Pablo Stanley" class="h-72 mx-auto lg:h-auto lg:w-2/6" />
                <p class="pt-10">Christian Connection Cards was developed by Dylan, who had the idea after 
                    learning about the popular card game 
                    <a class="text-primary" href="https://www.werenotreallystrangers.com/" target="_blank">We're Not Really Strangers (WNRS)</a>.
                    He thought to himself - wait, why don't we have this for church?<br>
                </p>
                <p class="py-5">And so, CCC was born.<br></p>
                <div class="divider"></div>
                <p class="text-xs">You can access the Github repo <a class="text-primary" href="https://github.com/dylanlim-jy/christian-connection-cards" target="_blank">here</a>.<br>
                    Illustrations by <a class="text-primary" href="https://iconscout.com/contributors/humaaans" target="_blank">Pablo Stanley</a> and <a href="https://thenounproject.com/browse/icons/term/plant/" target="_blank" title="Plant Icons" class="text-primary">Roman from Noun Project</a>.
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

cards/templates/cards/how_to_play.html
{% extends 'base.html' %}
{% load static %}

{% block title %}How To Play{% endblock title %}
{% block content %}
<section class="mx-auto px-5 md:px-20 min-w-5xl max-w-full py-10">
    <div class="hero">
        <div class="hero-content text-center lg:max-w-3xl">
            <div>
                <h1 class="text-3xl md:text-5xl font-black">How to Play</h1>
                <div class="flex flex-wrap items-center justify-center py-10">
                    <div class="tabs tabs-boxed">
                        <a id="twoPlayerTab" class="tab lg:w-32 font-bold tab-active">2 players</a> 
                        <a id="morePlayersTab" class="tab lg:w-32">3 - 6 players</a> 
                    </div>
                </div>
                <div id="twoPlayerTabContent">
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 1</h2>
    
                        <p>Questions are divided into 3 stages:</p>
                        <div class="ml-8">
                            <ul>
                                <li><span class="font-bold">Stage 1 'Perception'</span>: on self-image and how others perceive you.</li>
                                <li><span class="font-bold">Stage 2 'Connection'</span>: personal questions on your past, present, and eternal future.</li>
                                <li><span class="font-bold">Stage 3 'Edification'</span>: questions to help build one another up to the image of Christ.</li>
                                <br>
                                <li>You may choose how many questions per stage you want to play (minimum 3).</li>
                            </ul>
                        </div>
                    </div>

                    <div class="divider"></div>
                    
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 2</h2>
    
                        <p>Youngest player takes the first turn.<br>
                            Read out the first question to the other player who will respond.<br>
                            The active player is allowed to ask follow-up questions, but the responding player can decline to answer.
                        </p>
                    </div>

                    <div class="divider"></div>
    
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 3</h2>
    
                        <p>Swap players; the responding player is now the active player and will be the one asking the question.<br>
                            As both players progress through the stages, the questions are meant to become more personal.
                        </p>
                    </div>

                    <div class="divider"></div>
    
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 4</h2>
    
                        <p>At the end of the game, each player writes (or texts) a personal note to the other player.<br>
                            They are not allowed to read the note right away - read it once you have split up / left the room.
                        </p>
                    </div>
                </div>

                <div id="morePlayersTabContent" class="hidden">
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 1</h2>
    
                        <p>Questions are divided into 3 stages:</p>
                        <div class="ml-8">
                            <ul>
                                <li><span class="font-bold">Stage 1 'Perception'</span>: on self-image and how others perceive you.</li>
                                <li><span class="font-bold">Stage 2 'Connection'</span>: personal questions on your past, present, and eternal future.</li>
                                <li><span class="font-bold">Stage 3 'Edification'</span>: questions to help build one another up to the image of Christ.</li>
                                <br>
                                <li>You may choose how many questions per stage you want to play (minimum 3).</li>
                            </ul>
                        </div>
                    </div>

                    <div class="divider"></div>
                    
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 2</h2>
    
                        <p>Every player will some time writing down 3 impressions they have of every other player.<br>
                            Don't tell each other anything about this yet!
                        </p>
                    </div>

                    <div class="divider"></div>
                    
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 3</h2>
    
                        <p>The turn order starts from the youngest player to the oldest player.<br>
                            The first player will read out a question and every other player will respond.<br>
                            The active player is allowed to ask follow-up questions, but other players can decline to answer.
                        </p>
                    </div>

                    <div class="divider"></div>

                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 4</h2>
    
                        <p>Once the active player's turn is up, the turn goes to the second player, who reads the next question displayed.<br>
                            Once the question is read, every other player will respond.
                            As all players progress through the stages, the questions are meant to become more personal.
                        </p>
                    </div>

                    <div class="divider"></div>
    
                    <div class="text-left">
                        <h2 class="text-primary text-xl md:text-3xl font-extrabold mb-4">Step 5</h2>
    
                        <p>At the end of the game, each player shares the first impression of other players that they wrote earlier.<br>
                            After reading out the first impressions, players are also encouraged to share how that impression has changed over
                            the course of this game.
                        </p>
                    </div>
                </div>
                <div class="divider"></div>
                <a href="{% url 'cards:play' %}" class="btn btn-primary my-5">Ready to play?</a>
            </div>
        </div>
    </div>

    <script>
        const twoPlayerTab = document.getElementById("twoPlayerTab");
        const twoPlayerTabContent = document.getElementById("twoPlayerTabContent");
        const morePlayersTab = document.getElementById("morePlayersTab");
        const morePlayersTabContent = document.getElementById("morePlayersTabContent");

        morePlayersTab.addEventListener("click", function() {
            morePlayersTab.setAttribute('class', "tab lg:w-32 font-bold tab-active");
            twoPlayerTab.setAttribute('class', "tab lg:w-32");
            morePlayersTabContent.removeAttribute('class');
            twoPlayerTabContent.setAttribute('class', 'hidden');
        });

        twoPlayerTab.addEventListener("click", function() {
            twoPlayerTab.setAttribute('class', "tab lg:w-32 font-bold tab-active");
            morePlayersTab.setAttribute('class', "tab lg:w-32");
            twoPlayerTabContent.removeAttribute('class');
            morePlayersTabContent.setAttribute('class', 'hidden');
        });
    </script>
</section>

{% endblock content %}

cards/templates/cards/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Meaningful Conversations with your Church Family{% endblock title %}

{% block content %}
<section class="mx-auto px-5 md:px-20 min-w-5xl max-w-full py-10">
    <div class="hero h-fit">
        <div class="hero-content flex-col lg:flex-row gap-x-9">
          <img src="{% static 'images/' %}{{ random_image }}" alt="Illustration of a human by Pablo Stanley" class="h-72 w-auto lg:h-auto lg:w-2/6" />          
          <div class="lg:w-4/6 flex-col justify-start">
            <h1 class="text-3xl md:text-5xl font-black">A church card game designed for real connection.</h1>
            <p class="mt-4 mb-8">Dive deeper with your brothers and sisters in Christ. Explore and connect through meaningful conversations.</p>
            <div class="flex flex-row">

              <div class="card card-bordered p-8  min-w-full md:min-w-[50%]">
                  <form method="post">
                      {% csrf_token %}
                      <div class="form-control w-full mb-4">
                          <label class="label flex-row gap-x-2 justify-start">
                            <span class="label-text">Number of questions per stage: </span><span class="label-text" id="cardNumberSpan">{{ default_cards }}</span>
                          </label>
                          <input id="cardNumberRange" name="num_cards" type="range" min="3" max="{{ max_cards }}" step="3" value="{{ default_cards }}" class="range lg:range-xs range-primary max-w-xs" required/>
                      </div>
                      <div class="flex flex-col gap-y-4 lg:flex-row lg:gap-x-4 lg:items-center">
                        <input type="submit" class="btn btn-primary btn-outline" value="Start Playing"/>
                        <a href="{% url 'cards:how_to_play' %}" class="text-xs">How do I play?</a>
                      </div>
                  </form>
                </div>
            </div>
          </div>
        </div>
      </div>    
    <!-- Script to compute range input -->
    <script>
        // Get references to the input range and the span element
        const rangeInput = document.getElementById("cardNumberRange");
        const rangeValue = document.getElementById("cardNumberSpan");
      
        // Add an event listener to the input range
        rangeInput.addEventListener("input", function() {
          // Update the text content of the span with the current value of the range
          rangeValue.textContent = rangeInput.value;
        });
      </script>
</section>
{% endblock content %}

cards/templates/cards/play.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Play{% endblock title %}
{% block content %}
<section class="mx-auto px-5 md:px-20 min-w-5xl max-w-full py-10 relative">
    <div class="stats">
        <div class="stat">
            <div class="stat-desc">Question #<span id="currentQuestionNumber"></span> out of {{ num_cards }}</div>
            <div class="text-xl font-black md:text-2xl">Stage <span id="stageNumber">1</span>: <span id="stageDescription">Perception</span></div>
            <div class="text-xs md:text-base" id="stageDescriptionExtra">Learn how others perceive you and themselves.</div>
        </div>
        </div>

    <progress id="progressBar" class="progress progress-primary w-full mb-12" value="1" max="{{ num_cards }}"></progress>
    
    <div class="card card-bordered break-words h-[40vh] px-5 py-5 md:px-10 md:py-20 lg:px-20 lg:h-96">
        <p id="currentQuestion" class="text-2xl md:text-4xl lg:text-5xl font-extrabold text-center my-auto"></p>
    </div>
    
    <div class="grid grid-cols-2 w-full mt-12">
        <button id="previousQuestion" class="btn btn-outline rounded-r-none btn-disabled">Previous</button>
        <button id="nextQuestion" class="btn btn-outline rounded-l-none">Next</button>
        <label id="completeModalID" for="completeModal" class="btn btn-primary rounded-l-none hidden">End game</label>
      </div>    
    
    <input type="checkbox" id="completeModal" class="modal-toggle" />
    <div class="modal">
    <div class="modal-box">
        <img src="{% static 'images/plant.svg' %}" class="h-32 py-5" alt="Plant">
        <h3 class="font-bold text-lg">Thank you for playing!</h3>
        <p class="py-4">You may now proceed to write a note or text to your other player(s). Don't forget - you can only view this note after you leave each other's presence!</p>
        <div class="modal-action">
        <label for="completeModal" class="btn">Okay!</label>
        </div>
    </div>
    </div>

    {{ serialised_questions|json_script:"json-data"|safe }}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var currentQuestionIndex = 1;
            var questions = JSON.parse(JSON.parse(document.getElementById("json-data").textContent));
            
            const stageNumberElement = document.getElementById('stageNumber');
            const stageDescriptionElement = document.getElementById('stageDescription');
            const stageDescriptionExtraElement = document.getElementById('stageDescriptionExtra');
            const currentQuestionNumberElement = document.getElementById('currentQuestionNumber');
            const progressBarElement = document.getElementById('progressBar')
            const currentQuestionText = document.getElementById('currentQuestion');
            const previousButton = document.getElementById('previousQuestion');
            const nextButton = document.getElementById('nextQuestion');
            const completeModal = document.getElementById('completeModalID');

            function updateQuestion() {
                var currentQuestion = questions.find(a => a.index == currentQuestionIndex);
                stageNumberElement.innerText = currentQuestion['stage'];
                currentQuestionNumberElement.innerText = currentQuestion['index'];
                progressBarElement.setAttribute('value', currentQuestion['index']);
                currentQuestionText.innerText = currentQuestion['question'];
                
                if (currentQuestionIndex > 1) {
                    previousButton.classList.remove('btn-disabled');
                } else {
                    previousButton.classList.add('btn-disabled');
                };

                if (currentQuestionIndex < parseInt('{{ num_cards }}')) {
                    nextButton.classList.remove('hidden');
                    completeModal.classList.add('hidden');
                } else {
                    nextButton.classList.add('hidden');
                    completeModal.classList.remove('hidden');
                };

                if (currentQuestion['stage'] == 1) {
                    stageDescriptionElement.innerHTML = "Perception";
                    stageDescriptionExtraElement.innerHTML = "Learn how others perceive you and themselves.";
                } else if (currentQuestion['stage'] == 2) {
                    stageDescriptionElement.innerHTML = "Connection";
                    stageDescriptionExtraElement.innerHTML = "Explore each other's past, present, and hopes for our eternal future.";
                } else if (currentQuestion['stage'] == 3) {
                    stageDescriptionElement.innerHTML = "Edification";
                    stageDescriptionExtraElement.innerHTML = "Build and encourage each other up to the image of Christ.";
                };

            }

            function handlePreviousClick() {
                if (currentQuestionIndex > 1) {
                    currentQuestionIndex--;
                    updateQuestion();
                };
            }

            function handleNextClick() {
                if (currentQuestionIndex < parseInt('{{ num_cards }}')) {
                    currentQuestionIndex++;
                    updateQuestion();
                };
            }

            previousButton.addEventListener('click', handlePreviousClick);
            nextButton.addEventListener('click', handleNextClick);

            updateQuestion();
        });
    </script>

</section>

{% endblock content %}

cards/templates/cards/question_bank.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Question Bank{% endblock title %}
{% block content %}
<section class="mx-auto px-5 md:px-20 min-w-5xl max-w-full py-10">
    <div class="hero">
        <div class="hero-content lg:max-w-3xl text-center">
            <div>
                <h1 class="text-3xl md:text-5xl font-black">Question Bank</h1>
                <div class="overflow-x-scroll py-10">
                    <table class="table table-xs">
                      <thead>
                        <tr>
                          <th>#</th> 
                          <th>Stage</th> 
                          <th>Question</th> 
                        </tr>
                      </thead> 
                      <tbody>
                        {% for q in questions %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <td>{{ q.stage }}</td>
                                <td>{{ q.question }}</td>
                            </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

cards/templates/cards/suggest.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Suggest{% endblock title %}
{% block content %}
<section class="mx-auto px-5 md:px-20 min-w-5xl max-w-full py-10">
    <div class="hero">
        <div class="hero-content flex-col lg:max-w-3xl lg:flex-row-reverse gap-x-9">
          <div class="text-center lg:text-left">
            <h1 class="text-3xl md:text-5xl font-black">Suggest a question!</h1>
            <p class="py-6">
                Got an idea to add a question? Fill in the form and we'll consider adding it to our pool!
            </p>
          </div>
          <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
            <div class="card-body">
              <div class="form-control">
                <label class="label">
                  <span class="label-text">Email</span>
                </label>
                <input type="text" placeholder="name@email.com" class="input input-bordered" />
              </div>
              <div class="form-control w-full max-w-xs">
                <label class="label">
                  <span class="label-text">Question Stage</span>
                </label>
                <select class="select select-bordered">
                  <option disabled selected>select one</option>
                  <option>Stage 1: Perception</option>
                  <option>Stage 2: Connection</option>
                  <option>Stage 3: Edification</option>
                </select>
              </div>
              <div class="form-control">
                <label class="label">
                  <span class="label-text">Your suggested question</span>
                </label>
                <textarea class="textarea textarea-bordered h-24" placeholder="What Christian topic do you think I would preach really well on?"></textarea>
              </div>
              <div class="form-control mt-6">
                <button class="btn btn-primary">Submit</button>
              </div>
            </div>
          </div>
        </div>
      </div>
</section>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="emerald" style="touch-action: manipulation;">
	<head>
	<link rel="shortcut icon" href="{% static 'favicon/favicon.png' %}"/>
    <title>CCC | {% block title %}{% endblock title %}</title>
		<meta property="og:title" content="Christian Connection Cards">
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<meta name="description" property="og:description" content="Build meaningful relationships with strangers and familiar friends. Connect on a deeper level with your church family.">
		{% tailwind_css %}
	</head>

	<body class="px-5 lg:px-20">
		<div class="navbar bg-base-100 drop-shadow-md rounded-full sticky top-3 z-50">
			<div class="navbar-start">
				<div class="dropdown">
					<label tabindex="0" class="btn btn-ghost btn-circle">
					  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
					</label>
					<ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
						<li><a href="{% url 'cards:how_to_play' %}">How To Play</a></li>
						<li><a href="{% url 'cards:play' %}">Play</a></li>
						<div class="divider"></div>
						<li><a>Suggest (coming soon!)</a></li>
						<li><a href="{% url 'cards:about' %}">About</a></li>
					</ul>
				  </div>
			</div>
			<div class="navbar-center">
			  <a href="{% url 'cards:index' %}" class="btn btn-ghost normal-case hidden md:inline-flex text-md md:text-xl">CHRISTIAN CONNECTION CARDS</a> 
			  <a href="{% url 'cards:index' %}" class="btn btn-ghost normal-case md:hidden text-xl">CCC</a> 
			  <div class="badge badge-outline text-xs">BETA</div>
			</div>
			<div class="navbar-end">
				<label class="swap swap-rotate hidden md:inline-grid px-5">
					<input id="darkModeToggle" type="checkbox" style="display:none"/>
					<!-- sun icon -->
					<svg class="swap-on fill-current w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/></svg>
					<!-- moon icon -->
					<svg class="swap-off fill-current w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/></svg>
					</label>
			  </div>
		  </div>
		<!-- Content here -->
		{% block content %}{% endblock content %}
		
		  <script>
			document.addEventListener('DOMContentLoaded', function () {
				const darkModeToggle = document.getElementById('darkModeToggle');
				
				function updateDarkMode() {
					console.log(darkModeToggle.checked)
					if (darkModeToggle.checked == true) {
						document.querySelector('html').setAttribute('data-theme', 'dark');
					} else if (darkModeToggle.checked == false) {
						document.querySelector('html').setAttribute('data-theme', 'emerald');
					};
				}

				darkModeToggle.addEventListener('click', updateDarkMode);
			});
		  </script>
	</body>
</html>